# Generated by Django 3.1.4 on 2021-02-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casaeditrice',
            old_name='Nome',
            new_name='NomeCa',
        ),
        migrations.RenameField(
            model_name='collane',
            old_name='Nome',
            new_name='NomeCo',
        ),
        migrations.RenameField(
            model_name='tradautcur',
            old_name='Cognome',
            new_name='CognomeTr',
        ),
        migrations.RenameField(
            model_name='tradautcur',
            old_name='Nome',
            new_name='NazioneTr',
        ),
        migrations.RenameField(
            model_name='tradautcur',
            old_name='Nazione',
            new_name='NomeTr',
        ),
        migrations.RenameField(
            model_name='utenti',
            old_name='Cognome',
            new_name='CognomeUt',
        ),
        migrations.RenameField(
            model_name='utenti',
            old_name='Nome',
            new_name='NazioneUt',
        ),
        migrations.RenameField(
            model_name='utenti',
            old_name='Nazione',
            new_name='NomeUt',
        ),
        migrations.AlterField(
            model_name='postfazionepre',
            name='autPostfazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Post', to='libri.tradautcur'),
        ),
        migrations.AlterField(
            model_name='postfazionepre',
            name='autPrefazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Pre', to='libri.tradautcur'),
        ),
    ]
