# Generated by Django 3.1.4 on 2021-04-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestito',
            name='IDUtente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libri.utenti'),
        ),
    ]
