# Generated by Django 3.1.4 on 2021-03-18 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libri', '0002_auto_20210220_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestito',
            name='IDUtente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
